# Generated by Django 5.1.1 on 2025-01-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='working_hours',
        ),
    ]
