# Generated by Django 5.1.1 on 2025-04-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_min_delivery_time_offer_min_price'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offers.offerdetail'),
            preserve_default=False,
        ),
    ]
